spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql连接配置
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      username: admin
      password: admin
server:
  port: 8989