spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql连接配置
    url: jdbc:mysql://172.17.1.24:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: 172.17.1.20
      port: 27030
      database: xingli_hchdb
      username: xingli
      password: xingli
server:
  port: 8989